# Notes
These are just notes I used for constructing the TFP joints

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
tfd = tfp.distributions
tfb = tfp.bijectors
from tensorflow_probability.python.internal import tensorshape_util
import os, sys
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
tfp.__version__


'0.11.0'

In [2]:
import maxentep

In [3]:
start = np.array([[0.0, 10, 0, 0], [0, 0.0, 3, 0.], [0., 0.0, 0.0, 2.], [0., 0., 0., 1.]])
var = start / 2
i = tf.keras.Input((1,))
l, fxn = maxentep.recip_norm_mat_layer(i, start, var, 'foo')
model = tf.keras.Model(inputs=i, outputs=l)

In [4]:
d = model(tf.constant([0.]))
d.sample()

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.14858821, 0.2764082 , 0.50296175, 0.85609233], dtype=float32)>

In [5]:
s = fxn(d.sample(4))

In [6]:
tf.reduce_sum(s[0], axis=-1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [7]:
logits = np.array(np.random.normal(size=10)).astype(np.float32)

In [8]:
i =  tf.keras.Input((1,))
logits = np.array(np.random.normal(size=10)).astype(np.float32)
l,fxn = maxentep.categorical_normal_layer(i,logits, 0.2, 0.01, 'cn')

In [9]:
model = tf.keras.Model(inputs=i, outputs=l)
j = model(tf.constant([1.]))
print(j)
s = j.sample(2)
s, fxn(s)

tfp.distributions.Blockwise("functional_3_cn_dist_Blockwise", batch_shape=[], event_shape=[20], dtype=float32)


(<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 1.        , 0.        , 0.        ,
         0.21544923, 0.18797947, 0.20260102, 0.20197213, 0.19311608,
         0.20648181, 0.20502761, 0.20136331, 0.18662427, 0.20449673],
        [0.        , 1.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.18852605, 0.19995408, 0.2052992 , 0.20438798, 0.21570414,
         0.19563536, 0.19694388, 0.20094205, 0.20765504, 0.19835362]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 10), dtype=float32, numpy=
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.20136331, 0.        , 0.        ],
        [0.        , 0.19995408, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ]],
       dtype=float32)>)

In [10]:
j.log_prob(j.sample(5))

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([32.89832 , 32.52233 , 27.312704, 28.609951, 32.24034 ],
      dtype=float32)>

In [11]:
start = np.array([[0.0, 10, 0, 0], [0, 0.0, 3, 0.], [0., 0.0, 0.0, 2.], [0., 0., 0., 1.]])
var = start / 2
bs = np.concatenate((start[np.newaxis,...], start[np.newaxis,...]))
print(tf.where(bs > 0)[:,1:])


tf.Tensor(
[[0 1]
 [1 2]
 [2 3]
 [3 3]
 [0 1]
 [1 2]
 [2 3]
 [3 3]], shape=(8, 2), dtype=int64)


In [12]:
j = maxentep.recip_norm_mat_dist(start, var)

TypeError: recip_norm_mat_dist() missing 1 required positional argument: 'indices'

In [ ]:
j.log_prob(j.sample())

In [ ]:
x = j.log_prob(j.sample(5))

In [ ]:
print(j.sample(4))
#j.log_prob(j.sample())

In [ ]:
i =  tf.keras.Input((1,))
combined = np.stack((start, var))
print(combined.shape)
x  = maxentep.TrainableInputLayer(combined, constraint=maxentep.PositiveMaskedConstraint(combined > 0))(i)

In [ ]:
m = tf.keras.Model(inputs=i, outputs=x)
t = m(tf.constant([1., 1.]))
t

In [ ]:
t[0,0], t[0,1]

In [ ]:
i =  tf.keras.Input((1,))
l = maxentep.recip_norm_mat_layer(i, start, var, 'test')

In [ ]:
m = tf.keras.Model(inputs=i, outputs=l)

In [ ]:
m(tf.constant([1.]))

In [27]:
logits = np.array(np.random.normal(size=10)).astype(np.float32)
d = tfd.Bernoulli(logits)
d.sample(5)

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[1, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 1]])>

In [30]:
tfd.Independent(d, 1)

<tfp.distributions.Independent 'IndependentBernoulli' batch_shape=[] event_shape=[10] dtype=int32>